---
title: "Timing Quicksort An exporation of Time Complexity"
output: html_notebook
---
```{r}
part1 = read.csv("rawData/part1.csv")
part1B = read.csv("rawData/part1B.csv")
part2A= read.csv("rawData/part2A.csv")
part2B= read.csv("rawData/part2B.csv")
part2B_2 = read.csv("rawData/part2B_2.csv")
part2C= read.csv("rawData/part2C.csv")
part2D= read.csv("rawData/part2D.csv")
part2E = read.csv("rawData/part2E.csv")
part2F = read.csv("rawData/part2F.csv")
part3 = read.csv("rawData/part3.csv")
```
## Figure 1.1
```{r}
Hoare = part3$Hoare
Lomuto = part3$Lomuto
Hoare.mean = mean(part3$Hoare)
Lomuto.mean = mean(part3$Lomuto)

boxplot(Hoare, Lomuto, 
        horizontal = TRUE,
        names = c("Hoare", "Lomuto"),
        ylab="Partiton Scheme",
        xlab="Time Complexity (nanoseconds)",
        main="Figure 1.1: Hoare VS Lomuto Partitioning")
```
# Figure 2.1
```{r}
boxplot(part2A$X0, part2A$X25, part2A$X50, part2A$X75, part2A$X100, part2A$X125,
        horizontal = TRUE,
        xlab="Time Complexity (nanoseconds)",
        ylab="Partition After Length",
        names=c("O (Lomuto)", "25", "50", "75", "100", "125"),
        main="Figure 1.2: Spread 1")

labels <- c("O (Lomuto)", "25", "50", "75", "100", "125")
canidates <- c(mean(part2A$X0), mean(part2A$X25), mean(part2A$X50), mean(part2A$X75), mean(part2A$X100), mean(part2A$X125))
setNames(canidates, labels)
barplot(canidates)
c0mean <- mean(part2A$X0)
```
```{r}

mean(part2B$X50)
mean(part2A$X50)
```
## Figure 2.2
```{r}
part2Names=c(30, 50, 70, 90)
boxplot(part2B$X30, part2B$X50, part2B$X70, part2B$X90,
        xlab="Time Complexity (nanoseconds)",
        ylab="Partition After Length",
        names=part2Names,
        horizontal = TRUE,
        main="Spread 2")

```
## Figure 2.3
```{r}
means <- c(mean(part2B$X50), mean(part2A$X50), mean(part2C$X50))
labels <- c("Part2B", "Part2A", "Part 2C")
barplot(means, names=labels, main="A Comparision of Different Runs of Cut Off Value 50", 
        ylab="Time Complexity (nanoseconds)",
        xlab="Run")
```
## Figure 2.4
```{r}

boxplot(part2B_2$QuickThenInsert...30, part2B_2$QuickThenInsert...50, part2B_2$QuickThenInsert...70, part2B_2$QuickThenInsert...90,
        names = part2Names,
        xlab = "Time Complexity (nanoseconds)",
        ylab = "Partition After Length",
        main="Spread 2, Run 2",
        horizontal = TRUE)
```
## Table 2.1
```{r}
m50 <- mean(part2B_2$QuickThenInsert...50)
m70 <- mean(part2B_2$QuickThenInsert...70)

m50
m70

# Actual distance
m70-m50

# Relative difference
(m50-m70)/m70
(m70-m50)/m50
```
## Figure 2.5
```{r}
means <- c(mean(part2B$X50), mean(part2A$X50), mean(part2C$X50), mean(part2B_2$QuickThenInsert...50))
labels <- c("Part2B", "Part2A", "Part 2C", "Part2B_2")
barplot(means, names=labels, main="A Comparision of Different Runs of Cut Off Value 50, part 2", 
        ylab="Time Complexity (nanoseconds)",
        xlab="Run")
```
## Figure 2.6
```{r}
b2_1 = c(mean(part2B$X30), mean(part2B$X50), mean(part2B$X70), mean(part2B$X90))
b2_2 = c(mean(part2B_2$QuickThenInsert...30), mean(part2B_2$QuickThenInsert...50), mean(part2B_2$QuickThenInsert...70),  
         mean(part2B_2$QuickThenInsert...90))


plot(part2Names, b2_1, type="n", main="Spread 2, Run 1", xlab="Cut Off Value", ylab="Time Complexity (nanoseconds)")
lines(part2Names, b2_1, type="b")

plot(part2Names, b2_2, type="n", main="Spread 2, Run 2", xlab="Cut Off Value", ylab="Time Complexity (nanoseconds)")
lines(part2Names, b2_2, type="b")
```
## Figure 2.7
```{r}
boxplot(part2C$X50,part2C$X55, part2C$X60, part2C$X65, part2C$X70,
        xlab="Time Complexity (nanoseconds)",
        ylab="Partition After Length",
        names=c(50, 55, 60, 65, 70),
        horizontal = TRUE,
        main="Spread 3")

mean(part2C$X60)
(mean(part2A$X0) - mean(part2C$X60)) / mean(part2A$X0) 
```
## Figure 2.8
```{r}
means <- c(mean(part2C$X50), mean(part2C$X55), mean(part2C$X60), mean(part2C$X65), mean(part2C$X70))
sd(means)
table(means)

names = c(50, 55, 60, 65, 70)
plot(names,means, type="b", main="Means of Spread 3", xlab="Cut Off Value", ylab="Sample Mean Time Complexity (nanoseconds)")
lines(names, means, type="n")
```
## Figure 2.9
```{r}
boxplot(part2D$X55,part2D$X57, part2D$X59, part2D$X61, part2D$X63, part2D$X65,
        xlab="Time Complexity (nanoseconds)",
        ylab="Partition After Length",
        names=c(55,57,59,61,63,65),
        horizontal = TRUE,
        main="Spread 4")
```

```{r}
mean <- mean(part2D$X59)
mean
(c0mean - mean) / c0mean
```

## Figure 2.10
```{r}
means <- c(mean(part2D$X55), mean(part2D$X57), mean(part2D$X59), mean(part2D$X61), mean(part2D$X63), mean(part2D$X65))
names <- c(55,57,59,61,63,65)
        

plot(names, means, type="b", main="Means of Spread 4", xlab="Cut Off Value", ylab="Sample Mean Time Complexity (nanoseconds)")
lines(names, means, type="n")

```
## Figure 2.11
```{r}
boxplot(part2E$X57, part2E$X58, part2E$X59, part2E$X60, part2E$X61,
        xlab="Time Complexity (nanoseconds)",
        ylab="Partition After Length",
        names=c(57,58,59,60,61),
        horizontal = TRUE,
        main="Spread 5")
```

```{r}
mean <- mean(part2E$X59)
mean
(c0mean - mean)/c0mean
```
## Figure 2.12
```{r}
boxplot(part2F$Lomuto, part2F$QuickThenInsert...59,
        xlab="Time Complexity (nanoseconds)",
        ylab="Partition Scheme",
        names=c("Lomuto", "Cut off at 59"),
        horizontal = TRUE,
        main="Final Comparison")
```
## Figure 2.13
```{r}
l1 = part2A$X0
l2 = part2F$Lomuto
l3 = part3$Lomuto
c59A = part2F$QuickThenInsert...59
c59C = part2E$X59
c59B = part2D$X59

l = c(l1, l2, l3)
c = c(c59A, c59B, c59C)

boxplot(l, c,
        horizontal = TRUE,
        main = "Aggregate Comparison of Lomuto and Cut Off at 59",
        xlab = "Time Complexity (nanoseconds)",
        ylab = "Partition Scheme",
        names = c("Lomuto", "Cut Off at 59"))
```
## Figure 2.14
```{r}
boxplot(l1, l2, l3, c59A, c59B, c59C,
        main = "Comparison of All Runs, Lomuto and Cut Off at 59",
        xlab = "Time Complexity (nanoseconds)",
        ylab = "Partition Scheme",
        names = c("Lomuto 1", "Lomuto 2", "Lomuto 3", "Cut Off 1", "Cut Off 2", "Cut Off 3"),
        horizontal = TRUE)
```
## Table 2.2
```{r}
l.mean = mean(l)
c.mean = mean(c)
l.mean
c.mean
dist = l.mean - c.mean
dist
dist / l.mean
```


```{r}
m59 <- mean(part2F$QuickThenInsert...59)
ml <- mean(part2F$Lomuto)
m59
ml
(ml - m59) / ml

```
# Part 3
## Figure 3.1
```{r}
boxplot(part1$Lomuto, part1$MedianOfThree,
        horizontal = TRUE,
        names = c("Lomuto", "Median of Three"),
        main = "Median of Three VS Lomuto Partition",
        xlab = "Time Complexity (nanoseconds)",
        ylab = "Partition Scheme")

```

```{r}
lmean = mean(part1$Lomuto)
mmean = mean(part1$MedianOfThree)

loss = (lmean - mmean) / lmean

lmean
mmean
loss
```
# Part 4
## Figure 4.1
```{r}

bestShot= as.numeric(part1B$BestShot.59)
lomuto = as.numeric(part1B$Lomuto)

boxplot(bestShot, lomuto, horizontal = TRUE,
        names = c("Best Shot", "Lomuto"),
        xlab = "Time Complexity (nanoseconds)",
        ylab = "Contender",
        main = "Combination of Median of Three and Cut Off at 59")
quantile(bestShot)
quantile(lomuto)
```
## Table 4.1
```{r}
bestShot.mean = mean(bestShot)
lomuto.mean = mean(lomuto)

bestShot.mean
lomuto.mean
(lomuto.mean - bestShot.mean) / lomuto.mean
```
# Part 5
## Figure 5.1
```{r}

```


```{r}    
control <- l
hoare <- Hoare
cutoff <- c
median <- part1$MedianOfThree
library <

boxplot(hoare, median, control, cutoff, bestShot,
        names = c("Hoare", "Median of Three", "Lomuto", "Cut Off at 59", "Best Shot", "Library"),
        main = "Aggregate Comparison of All Races",
        ylab = "Contender",
        xlab = "Time Complexity (nanoseconds)")
```

